Celebrity.delete_all
Friend.delete_all
Encounter.delete_all

adele=Celebrity.create(name: "Adele", image:"https://cdn.images.express.co.uk/img/dynamic/126/590x/secondary/Adele-weight-loss-838409.jpg", age: 30, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

america_ferrara=Celebrity.create(name: "America Ferrara", image:"https://static-ssl.businessinsider.com/image/56cde40f6e97c62e008b95d2-1143-857/america.jpg", age: 34, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

angelina_jolie=Celebrity.create(name: "Angelina Jolie", image:"http://www.enneagrammaintegrale.it/uploads/2016-11-18/1200-0/T2%20Angelina%20Jolie.jpg", age: 43, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

aubrey_plaza=Celebrity.create(name: "Aubrey Plaza", image:"https://m.media-amazon.com/images/M/MV5BMjIyMzYyMjQ5OV5BMl5BanBnXkFtZTcwMTA0MTkxNw@@._V1_SY1000_CR0,0,697,1000_AL_.jpg", age: 34, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 1, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

beyonce=Celebrity.create(name: "Beyonce", image:"https://aisrtl-a.akamaihd.net/masters/1051703/2400x1350/beyonce-ruehrender-glueckwunsch-zum-37-geburtstag-von-mama-tina-knowles.jpg", age: 37, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

brenda_song=Celebrity.create(name: "Brenda Song", image:"https://www.cinemartmagazine.it/wp-content/uploads/2018/03/Brenda-Song.jpg", age: 30, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 4, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

cara_delevilgne=Celebrity.create(name:"Cara Delevilgne", image:"https://pm1.narvii.com/6555/c7061992443375d0aa2d3a5c368bda10f04852e5_hq.jpg", age: 29, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

cardi_b=Celebrity.create(name: "Cardi B", image:"http://detroitnewswatch.org/wp-content/uploads/2018/07/s091697913.jpg", age: 24, arched_eyebrows: 0, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 3, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

charlize_theron=Celebrity.create(name: "Charlize Theron", image:"https://www.wallofcelebrities.com/celebrity/charlize-theron/pictures/xxlarge/charlize-theron_2915.jpg", age: 50, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 0, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

dewanda_wise=Celebrity.create(name: "Dewanda Wise", image:"https://cdn1.thr.com/sites/default/files/2018/01/gettyimages-873757432_copy_-_h_2017.jpg", age: 23, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

drew_barrymore=Celebrity.create(name: "Drew Barrymore", image:"http://d1hg6wdwbisxfa.cloudfront.net/wp-content/uploads/2018/08/15105623/drew-barrymore.jpg", age: 33, arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 1, heavy_makeup: 0, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

ellen_degeneris=Celebrity.create(name:"Ellen Degeneris", image:"https://pbs.twimg.com/media/DpHFc9dVAAE6k2T.jpg", age: 39, arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 0, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

emma_stone=Celebrity.create(name:"Emma Stone", image:"https://i0.wp.com/akns-images.eonline.com/eol_images/Entire_Site/2016622/rs_1024x759-160722115725-1024.Emma-Stone-Accutaine-Skin-Story.jl.072116.jpg", age: 33, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

emma_watson=Celebrity.create(name: "Emma Watson", image:"https://i.imgur.com/1tHQDWe.jpg", age: 16, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

federica_nargi=Celebrity.create(name: "Federica Nargi", image:"https://www.iosmode.com/wp-content/uploads/2016/05/Federica-Nargi-iPhone-Wallpaper.jpg", age: 24, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 1, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

halle_berry=Celebrity.create(name: "Halle Berry", image:"https://assets.rbl.ms/13853390/980x.jpg", age: 15, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 2, receding_hairline: 1, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

jennifer_aniston=Celebrity.create(name: "Jennifer Aniston", image:"http://upload.wikimedia.org/wikipedia/commons/1/1a/Jennifer_Aniston_2011_%28cropped_2%29.jpg", age: 34, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

jennifer_lawrence=Celebrity.create(name: "Jennifer Lawrence", image:"https://celebritypics.info/images/2018/06/most-famous-commercial-actors-luxury-jennifer-lawrence-actor-actress-actress-actress-of-most-famous-commercial-actors.jpg", age: 14, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

jennifer_lopez=Celebrity.create(name: "Jennifer Lopez", image:"https://m.media-amazon.com/images/M/MV5BMTY0OTY3ODA3OV5BMl5BanBnXkFtZTcwMzMyMzQ1NQ@@._V1_UY317_CR32,0,214,317_AL_.jpg", age: 14, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 3, receding_hairline: 1, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

jessica_biel=Celebrity.create(name: "Jessica Biel", image:"https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTE4MDAzNDEwODAwMTgyNzk4/jessica-biel-16730224-1-402.jpg", age: 38, arched_eyebrows: 0, big_lips: 1, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

joan_chen=Celebrity.create(name: "Joan Chen", image:"https://cdn.cumpleañosdefamosos.com/gallery/2017/1/joan-chen/joan-chen-a-a-a-162666-fotos-de-joan-chen.jpg", age: 21, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 4, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

julia_roberts=Celebrity.create(name: "Julia Roberts", image:"https://cache.marieclaire.fr/data/photo/w1000_ci/4u/julia-roberts.jpg", age: 45, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

katy_perry=Celebrity.create(name: "Katy Perry", image:"https://akphoto4.ask.fm/821/159/138/-79996993-20aql8p-j6i9i3rge2r0ft5/original/Screenshot_20160624211843.jpg", age: 28, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

kim_kardashian=Celebrity.create(name: "Kim Kardashian", image:"https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1440,w_2560,x_0,y_0/dpr_2.0/c_limit,w_740/fl_lossy,q_auto/v1536110105/kimmy_o1iyhu", age: 17, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

krysten_ritten=Celebrity.create(name:"Krysten Ritten", image:"https://iv1.lisimg.com/image/16241549/740full-krysten-ritter.jpg", age: 14, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

lucy_liu=Celebrity.create(name: "Lucy Liu", image:"https://i.pinimg.com/236x/d1/80/07/d18007db2ea7d2e09cda862b47ea11d0.jpg", age: 42, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 4, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

mariagrazia_cucinotta=Celebrity.create(name: "Mariagrazia Cucinotta", image:"http://radiostereosantagata.it/wp-content/uploads/2018/09/maria-grazia-cucinotta143784094.jpg", age: 44, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

megane_fox=Celebrity.create(name: "Megane Fox", image:"https://img.hdocache.ru/2017/10/27/thumbnail/ff2c046aa2fe2eee56fb746802f3b05f-megan-fox-opens-up-about-being-sacked-from-transformers.jpg", age: 19, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

melania_trump=Celebrity.create(name: "Melania Trump", image:"http://www.whispereye.com/wp-content/uploads/2018/05/Melania-Trump-1.jpg", age: 16, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 3, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

meryl_streep=Celebrity.create(name: "Meryl Streep", image:"https://m.media-amazon.com/images/M/MV5BMTU4Mjk5MDExOF5BMl5BanBnXkFtZTcwOTU1MTMyMw@@._UY400_.jpg", age: 31, arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 0, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

mia_khalifa=Celebrity.create(name:"Mia Khalifa", image:"https://1.bp.blogspot.com/-riCxpQ2MkgY/Vzy7E3fQwmI/AAAAAAAACyg/iSFdyVLlRYs483z9da94wxxShqxl7IUgQCLcB/s1600/mia-khalifa-images-photos-9fd90c6f2ec07813757a880b9f05e5e4-large-1039325.jpg", age: 27, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: 2, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

monica_bellucci=Celebrity.create(name: "Monica Bellucci", image:"https://uznayvse.ru/images/celebs/2018/3/belluchi_big.jpg", age: 22, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

naomi_campbell=Celebrity.create(name: "Naomi Campbell", image:"http://i2.haber7.net//haber/haber7/photos/2018/46/bGvO8_1542021150_3473.jpg", age: 25, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 1, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

nathalie_emannuel=Celebrity.create(name: "Nathalie Emannuel", image:"https://www.naijaonpoint.com/wp-content/uploads/2018/07/Nathalie-Emmanuel.jpg", age: 22, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

nicki_minaj=Celebrity.create(name: "Nicki Minaj", image:"https://pbs.twimg.com/media/DkVMBqJXgAE_LfB.jpg", age: 33, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 4, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

nicole_kidman=Celebrity.create(name: "Nicole Kidman", image:"http://www.calikusuhaber.com/imagestore/resimler/haber-nicole-kidman-a-buyuk-onur-1538490240.jpg", age: 13, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

oprah=Celebrity.create(name:"Oprah", image:"https://cdn1.thr.com/sites/default/files/2013/12/issue_45_a_wie_oprah_h.jpg", age: 44, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 1, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

rhianna=Celebrity.create(name: "Rhianna", image:"https://trueebullcom.files.wordpress.com/2018/02/ririr.jpg?w=900", age: 14, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 3, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

roasario_dawson=Celebrity.create(name:"Rosario Dawson", image:"https://celebpic.info/images/2018/08/most-beautiful-actresses-under-20-fresh-35-most-beautiful-black-female-celebrities-hottest-black-women-pics-of-most-beautiful-actresses-under-20.jpg", age: 23, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

sandra_bullock=Celebrity.create(name:"Sandra Bullock", image:"https://journal.hautehorlogerie.org/wp-content/uploads/2018/07/Sandra-Bullock-c.jpg", age: 25, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

scarlett_johansson=Celebrity.create(name: "Scarlett Johansson", image:"https://pm1.narvii.com/6897/f16979afb6d9916fedf12a29fccadf1df083c00cr1-1080-807v2_hq.jpg", age: 22, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

sophia_vergara=Celebrity.create(name:"Sofia Vergara", image:"https://3.bp.blogspot.com/-qczjAzb5LA8/W22oa-n92JI/AAAAAAAAjyE/kQVS5SHR8UQbIqogAEoOexWuTxXfs44kQCLcBGAs/s1600/sofia-vergara.jpg", age: 38, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 1, race: 3, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

sophie_tuner=Celebrity.create(name:"Sophie Turner", image:"https://cdn.cliqueinc.com/cache/posts/258390/tyra-banks-pacific-palisades-home-258390-1527007456211-main.700x0c.jpg", age: 21, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

taylor_swift=Celebrity.create(name:"Taylor Swift", image:"https://www.grammy.com/sites/com/files/styles/image_landscape_hero/public/taylorswift-hero-510837066.jpg?itok=-KPdXpCe", age: 17, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

emily_clarke=Celebrity.create(name: "Emily Clarke", image:"https://noescinetodoloquereluce.com/wp-content/uploads/2016/11/emilia-clarke-800x445.jpg", age: 16, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

thandie_newton=Celebrity.create(name: "Thandie Newton", image:"https://i.pinimg.com/originals/09/f2/08/09f2088f642e48765b79bf9280e40247.jpg", age: 17, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

tyra_banks=Celebrity.create(name: "Tyra Banks", image:"https://cdn.cliqueinc.com/cache/posts/258390/tyra-banks-pacific-palisades-home-258390-1527007456211-main.700x0c.jpg", age: 18, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 4, receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

zazie_beetz=Celebrity.create(name:"Zazie Beetz", image:"https://kenh14cdn.com/2018/2/7/dsc4517-15179857746511996920431.jpg", age: 21, arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 0, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

zoe_kravitz=Celebrity.create(name: "Zoe Kravitz", image:"https://i.pinimg.com/236x/6c/44/d2/6c44d2aef996fa7174849e0bae5a16c3--smoked-eyes-center-part.jpg", age: 19, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 2, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

cdn=Friend.create(name:"Crystal", image: "https://i1.wp.com/omega-rose.com/wp-content/uploads/2016/07/image-2.jpeg", age: 24 , arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0,brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

srey=Friend.create(name:"Tiffany", image: "http://www.srey-saat.com/wp-content/uploads/2018/04/Ha-Nui-Lee-Top-Most-Popular-Beautiful-Asian-Women-2018.jpg", age: 29 , arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: 1 , receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

tucu=Friend.create(name:"Amber", image:"http://www.tucumanalas7.com.ar/u/fotografias/m/2018/8/21/f620x350-79713_110731_25.jpg",age: 31 , arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: 4 , receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0, gender: 0, beard: 0, mustache: 0)

truelove=Friend.create(name:"Brenda", image:"https://truelovedates.com/wp-content/uploads/2013/03/looking-up-1.jpg",age: 25 , arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0,brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0,straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

atila=Friend.create(name:"Angel", image:"https://atilambalaj.com/wp-content/uploads/parser/short-hairstyles-for-black-women-natural-hair-1.jpg", age: 27 , arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1, gender: 0, beard: 0, mustache: 0)

johnny_depp=Celebrity.create(age: 39, name: "Johnny Depp", image: "https://www.irishtimes.com/polopoly_fs/1.3560652.1531256350!/image/image.jpg_gen/derivatives/ratio_16x9_w1200/image.jpg", beard: 1, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

bradley_cooper=Celebrity.create(age: 53, name: "Bradley Cooper", image: "https://api.mbtidatabase.com/profile_images/14694.png", beard: 1, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

aziz_ansari=Celebrity.create(age: 30, name: "", image: "https://pixel.nymag.com/imgs/daily/vulture/2017/01/10/10-aziz-ansari.w330.h330.jpg", beard: 1, big_lips: 1, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

obama=Celebrity.create(age: 42, name: "Obama", image: "https://image.tmdb.org/t/p/original/j9Z09FKsSdFj8zG8cKDM5FMqs0Q.jpg", beard: 1, big_lips: 0, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 4, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

aaron_paul=Celebrity.create(age: 45, name: "AAron Paul", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Aaron_Paul_Berlinale_2014_%28cropped%29.jpg/220px-Aaron_Paul_Berlinale_2014_%28cropped%29.jpg", beard: 1, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

benedict_cumberbatch=Celebrity.create(age: 39, name: "Benedict CumberBatch", image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTIzNjEzMTg5MzA5MzY3ODIy/benedict_cumberbatchjpg.jpg", beard: 0, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 0, narrow_eyes: 1, pale_skin: 1, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

adam_brody=Celebrity.create(age: 38, name: "Adam Brody", image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTIwNjA4NjM0MDg2Nzg2NTcy/adam-brody-16242348-1-402.jpg", beard: 1, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 0, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

denzel_washington=Celebrity.create(age: 47, name: "Denzel Washington", image: "http://www.celebritiesnetworth.org/wp-content/uploads/2013/02/Denzel-Washington.jpg", beard: 1, big_lips: 1, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

donald_glover=Celebrity.create(age: 38, name: "Donald Glover", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Donald_Glover_TIFF_2015.jpg/220px-Donald_Glover_TIFF_2015.jpg", beard: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 4, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

eddie_redmanye=Celebrity.create(age: 35, name: "Eddie Redmanye", image: "https://m.media-amazon.com/images/M/MV5BMTU0MjEyNzQyM15BMl5BanBnXkFtZTcwMTc4ODUxOQ@@._V1_.jpg", beard: 0, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 0, narrow_eyes: 1, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

george_clooney=Celebrity.create(age: 55, name: "George Clooney", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/George_Clooney_2016.jpg/220px-George_Clooney_2016.jpg", beard: 1, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

cristiano_ronaldo=Celebrity.create(age: 24, name: "Cristiano Ronaldo", image: "https://sport360.com/wp-content/uploads/2018/06/CristianoRonaldo-3.jpg", beard: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

jay_z=Celebrity.create(age: 33, name: "Jay Z", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Jay-Z_%40_Shawn_%27Jay-Z%27_Carter_Foundation_Carnival_%28crop_2%29.jpg/220px-Jay-Z_%40_Shawn_%27Jay-Z%27_Carter_Foundation_Carnival_%28crop_2%29.jpg", beard: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

floyd_mayweather=Celebrity.create(age: 30, name: "Floyd Mayweather", image: "https://www.jetpunk.com/img/user-photo-library/86/86a4054711-450.jpg", beard: 1, big_lips: 1, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

jayden_smith=Celebrity.create(age: 26, name: "Jayden Smith", image: "https://toofab.akamaized.net/2018/08/02/jaden-smith-main-getty-810x610.jpg", beard: 1, big_lips: 1, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 4, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

justin_bieber=Celebrity.create(age: 30, name: "Justin Bieber", image: "https://www.biography.com/.image/t_share/MTM2OTI2NTkwNzE3MTQyNjIz/justin_bieber_2015_photo_courtesy_dfree_shutterstock_348418241jpg.jpg", beard: 0, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

leonardo_di_capirio=Celebrity.create(age: 30, name: "Leonardo Di Caprio", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Leonardo_DiCaprio_January_2014.jpg/212px-Leonardo_DiCaprio_January_2014.jpg", beard: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

jason_momoa=Celebrity.create(age: 44, name: "Jason Momoa", image: "https://akns-images.eonline.com/eol_images/Entire_Site/2018630/rs_634x1024-180730133307-634-jason-momoa-073018.jpg", beard: 1, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

robert_downey_jr=Celebrity.create(age: 41, name: "Robert Downey JR", image: "https://androidandme.com/wp-content/uploads/2013/06/robert_downey_jr-630x387.jpg", beard: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

jake_gyllenhall=Celebrity.create(age: 29, name: "Jake Gyllenhall", image: "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNzk1MjAyMDYy/jake-gyllenhaal-16242387-1-402.jpg", beard: 0, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

lebron_james=Celebrity.create(age: 32, name: "Lebron James", image: "http://media.graytvinc.com/images/810*455/80702E00-UYZHG.jpg", beard: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

ryan_gosling=Celebrity.create(age: 37, name: "Ryan Gosling", image: "https://i.imgflip.com/1484h2.jpg", beard: 1, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

tom_holland=Celebrity.create(age: 38, name: "Tom Holland", image: "https://www.biography.com/.image/t_share/MTQ4MTUwOTQyMDE1OTU2Nzk4/tom-holland-photo-jason-kempin-getty-images-801510482-profile.jpg", beard: 0, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

steve_buscemi=Celebrity.create(age: 55, name: "Steve Buscemi", image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTIwNjA4NjMzNTY5NjQxOTk2/steve-buscemi-204410-1-402.jpg", beard: 0, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

tom_cruise=Celebrity.create(age: 33, name: "Tom Cruise", image: "https://pixel.nymag.com/imgs/daily/vulture/2017/06/14/14-tom-cruise.w700.h700.jpg", beard: 0, big_lips: 0, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 0, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

kit_harington=Celebrity.create(age: 34, name: "Kit Harrington", image: "http://cdnau.ibtimes.com/sites/au.ibtimes.com/files/styles/v2_article_large/public/2016/03/08/kit-harington-game-thrones.jpg", beard: 1, big_lips: 0, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)


mike=Friend.create(name: "Mike", image: "http://yourblackworld.net/wp-content/uploads/2018/09/Stinnett-Head-Shot-C-e1536699434886-1000x675.jpg", age: 50, arched_eyebrows: 0, beard: 1, big_lips: 0, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 1, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)


jason=Friend.create(name: "Jason", image: "https://imageshack.com/a/img923/7060/JPiK5D.jpg", age: 20, arched_eyebrows: 0, beard: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: 2, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

howard=Friend.create(name: "Howard", image: "https://imageshack.com/a/img923/7973/ZoauCW.jpg", age: 28, arched_eyebrows: 0, beard: 0, big_lips: 0, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 1, mustache: 0, narrow_eyes: 1, pale_skin: 1, pointy_nose: 0, race: 4, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

diego=Friend.create(name: "Diego", image: "https://imageshack.com/a/img922/6420/6MlcJy.jpg", age: 20, arched_eyebrows: 0, beard: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0 )

luis=Friend.create(name: "Luis", image: "https://imageshack.com/a/img923/7244/HZxNBk.jpg", age: 33, arched_eyebrows: 0, beard: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, gender: 1, heavy_makeup: 0, high_cheekbones: 0, mustache: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: 1, receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0 )
