Celebrity.delete_all
Friend.delete_all

adele=Celebrity.create(name: "Adele", image:"https://cdn.images.express.co.uk/img/dynamic/126/590x/secondary/Adele-weight-loss-838409.jpg", age: 30, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

america_ferrara=Celebrity.create(name: "America Ferrara", image:"https://static-ssl.businessinsider.com/image/56cde40f6e97c62e008b95d2-1143-857/america.jpg", age: 34, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

angelina_jolie=Celebrity.create(name: "Angelina Jolie", image:"http://www.enneagrammaintegrale.it/uploads/2016-11-18/1200-0/T2%20Angelina%20Jolie.jpg", age: 43, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

aubrey_plaza=Celebrity.create(name: "Aubrey Plaza", image:"https://m.media-amazon.com/images/M/MV5BMjIyMzYyMjQ5OV5BMl5BanBnXkFtZTcwMTA0MTkxNw@@._V1_SY1000_CR0,0,697,1000_AL_.jpg", age: 34, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "white", receding_hairline: 1, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)

beyonce=Celebrity.create(name: "Beyonce", image:"https://aisrtl-a.akamaihd.net/masters/1051703/2400x1350/beyonce-ruehrender-glueckwunsch-zum-37-geburtstag-von-mama-tina-knowles.jpg", age: 37, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "black", receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

brenda_song=Celebrity.create(name: "Brenda Song", image:"https://www.cinemartmagazine.it/wp-content/uploads/2018/03/Brenda-Song.jpg", age: 30, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "asian", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)

cara_delevilgne=Celebrity.create(name:"Cara Delevilgne", image:"https://pm1.narvii.com/6555/c7061992443375d0aa2d3a5c368bda10f04852e5_hq.jpg", age: 29, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

cardi_b=Celebrity.create(name: "Cardi B", image:"http://detroitnewswatch.org/wp-content/uploads/2018/07/s091697913.jpg", age: 24, arched_eyebrows: 0, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "hispanic", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

charlize_theron=Celebrity.create(name: "Charlize Theron", image:"https://www.wallofcelebrities.com/celebrity/charlize-theron/pictures/xxlarge/charlize-theron_2915.jpg", age: 50, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 0, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

dewanda_wise=Celebrity.create(name: "Dewanda Wise", image:"https://cdn1.thr.com/sites/default/files/2018/01/gettyimages-873757432_copy_-_h_2017.jpg", age: 23, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "black", receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

drew_barrymore=Celebrity.create(name: "Drew Barrymore", image:"http://d1hg6wdwbisxfa.cloudfront.net/wp-content/uploads/2018/08/15105623/drew-barrymore.jpg", age: 33, arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 1, heavy_makeup: 0, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

ellen_degeneris=Celebrity.create(name:"Ellen Degeneris", image:"https://pbs.twimg.com/media/DpHFc9dVAAE6k2T.jpg", age: 39, arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 0, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

emma_stone=Celebrity.create(name:"Emma Stone", image:"https://i0.wp.com/akns-images.eonline.com/eol_images/Entire_Site/2016622/rs_1024x759-160722115725-1024.Emma-Stone-Accutaine-Skin-Story.jl.072116.jpg", age: 33, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

emma_watson=Celebrity.create(name: "Emma Watson", image:"https://i.imgur.com/1tHQDWe.jpg", age: 16, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

federica_nargi=Celebrity.create(name: "Federica Nargi", image:"https://www.iosmode.com/wp-content/uploads/2016/05/Federica-Nargi-iPhone-Wallpaper.jpg", age: 24, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 1, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

halle_berry=Celebrity.create(name: "Halle Berry", image:"https://assets.rbl.ms/13853390/980x.jpg", age: 15, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "black", receding_hairline: 1, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)

# jennifer_aniston=Celebrity.create(name: "Jennifer Aniston", image:"http://upload.wikimedia.org/wikipedia/commons/1/1a/Jennifer_Aniston_2011_%28cropped_2%29.jpg", age: 34, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)
#
# jennifer_lawrence=Celebrity.create(name: "Jennifer Lawrence", image:"https://celebritypics.info/images/2018/06/most-famous-commercial-actors-luxury-jennifer-lawrence-actor-actress-actress-actress-of-most-famous-commercial-actors.jpg", age: 14, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)
#
# jennifer_lopez=Celebrity.create(name: "Jennifer Lopez", image:"https://m.media-amazon.com/images/M/MV5BMTY0OTY3ODA3OV5BMl5BanBnXkFtZTcwMzMyMzQ1NQ@@._V1_UY317_CR32,0,214,317_AL_.jpg", age: 14, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "hispanic", receding_hairline: 1, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)
#
# jessica_biel=Celebrity.create(name: "Jessica Biel", image:"https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTE4MDAzNDEwODAwMTgyNzk4/jessica-biel-16730224-1-402.jpg", age: 38, arched_eyebrows: 0, big_lips: 1, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)
#
# joan_chen=Celebrity.create(name: "Joan Chen", image:"https://cdn.cumpleañosdefamosos.com/gallery/2017/1/joan-chen/joan-chen-a-a-a-162666-fotos-de-joan-chen.jpg", age: 21, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "asian", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)
#
# julia_roberts=Celebrity.create(name: "Julia Roberts", image:"https://cache.marieclaire.fr/data/photo/w1000_ci/4u/julia-roberts.jpg", age: 45, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)
#
# katy_perry=Celebrity.create(name: "Katy Perry", image:"https://akphoto4.ask.fm/821/159/138/-79996993-20aql8p-j6i9i3rge2r0ft5/original/Screenshot_20160624211843.jpg", age: 28, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

# kim_kardashian=Celebrity.create(name: "Kim Kardashian", image:"https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1440,w_2560,x_0,y_0/dpr_2.0/c_limit,w_740/fl_lossy,q_auto/v1536110105/kimmy_o1iyhu", age: 17, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)
#
# krysten_ritten=Celebrity.create(name:"Krysten Ritten", image:"https://iv1.lisimg.com/image/16241549/740full-krysten-ritter.jpg", age: 14, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)
#
# lucy_liu=Celebrity.create(name: "Lucy Liu", image:"https://i.pinimg.com/236x/d1/80/07/d18007db2ea7d2e09cda862b47ea11d0.jpg", age: 42, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "asian", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 1)
#
# mariagrazia_cucinotta=Celebrity.create(name: "Mariagrazia Cucinotta", image:"http://radiostereosantagata.it/wp-content/uploads/2018/09/maria-grazia-cucinotta143784094.jpg", age: 44, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)
#
# megane_fox=Celebrity.create(name: "Megane Fox", image:"https://img.hdocache.ru/2017/10/27/thumbnail/ff2c046aa2fe2eee56fb746802f3b05f-megan-fox-opens-up-about-being-sacked-from-transformers.jpg", age: 19, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 1)
#
# melania_trump=Celebrity.create(name: "Melania Trump", image:"http://www.whispereye.com/wp-content/uploads/2018/05/Melania-Trump-1.jpg", age: 16, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "hispanic", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

meryl_streep=Celebrity.create(name: "Meryl Streep", image:"https://m.media-amazon.com/images/M/MV5BMTU4Mjk5MDExOF5BMl5BanBnXkFtZTcwOTU1MTMyMw@@._UY400_.jpg", age: 31, arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 0, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "white", receding_hairline: 1, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 0)

mia_khalifa=Celebrity.create(name:"Mia Khalifa", image:"https://1.bp.blogspot.com/-riCxpQ2MkgY/Vzy7E3fQwmI/AAAAAAAACyg/iSFdyVLlRYs483z9da94wxxShqxl7IUgQCLcB/s1600/mia-khalifa-images-photos-9fd90c6f2ec07813757a880b9f05e5e4-large-1039325.jpg", age: 27, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: "black", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

monica_bellucci=Celebrity.create(name: "Monica Bellucci", image:"https://uznayvse.ru/images/celebs/2018/3/belluchi_big.jpg", age: 22, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

naomi_campbell=Celebrity.create(name: "Naomi Campbell", image:"http://i2.haber7.net//haber/haber7/photos/2018/46/bGvO8_1542021150_3473.jpg", age: 25, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 1, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: "black", receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

nathalie_emannuel=Celebrity.create(name: "Nathalie Emannuel", image:"https://www.naijaonpoint.com/wp-content/uploads/2018/07/Nathalie-Emmanuel.jpg", age: 22, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "black", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

nicki_minaj=Celebrity.create(name: "Nicki Minaj", image:"https://pbs.twimg.com/media/DkVMBqJXgAE_LfB.jpg", age: 33, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "asian", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

nicole_kidman=Celebrity.create(name: "Nicole Kidman", image:"http://www.calikusuhaber.com/imagestore/resimler/haber-nicole-kidman-a-buyuk-onur-1538490240.jpg", age: 13, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

oprah=Celebrity.create(name:"Oprah", image:"https://cdn1.thr.com/sites/default/files/2013/12/issue_45_a_wie_oprah_h.jpg", age: 44, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 1, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: "black", receding_hairline: 1, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

rhianna=Celebrity.create(name: "Rhianna", image:"https://trueebullcom.files.wordpress.com/2018/02/ririr.jpg?w=900", age: 14, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "hispanic", receding_hairline: 1, rosy_cheeks: 0, straight_hair: 1, wavy_hair: 0)

roasario_dawson=Celebrity.create(name:"Rosario Dawson", image:"https://celebpic.info/images/2018/08/most-beautiful-actresses-under-20-fresh-35-most-beautiful-black-female-celebrities-hottest-black-women-pics-of-most-beautiful-actresses-under-20.jpg", age: 23, arched_eyebrows: 1, big_lips: 1, big_nose: 1, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 0, race: "black", receding_hairline: 1, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)

sandra_bullock=Celebrity.create(name:"Sandra Bullock", image:"https://journal.hautehorlogerie.org/wp-content/uploads/2018/07/Sandra-Bullock-c.jpg", age: 25, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

scarlett_johansson=Celebrity.create(name: "Scarlett Johansson", image:"https://pm1.narvii.com/6897/f16979afb6d9916fedf12a29fccadf1df083c00cr1-1080-807v2_hq.jpg", age: 22, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)

sophia_vergara=Celebrity.create(name:"Sofia Vergara", image:"https://3.bp.blogspot.com/-qczjAzb5LA8/W22oa-n92JI/AAAAAAAAjyE/kQVS5SHR8UQbIqogAEoOexWuTxXfs44kQCLcBGAs/s1600/sofia-vergara.jpg", age: 38, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 1, pale_skin: 0, pointy_nose: 1, race: "hispanic", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

sophie_tuner=Celebrity.create(name:"Sophie Turner", image:"https://cdn.cliqueinc.com/cache/posts/258390/tyra-banks-pacific-palisades-home-258390-1527007456211-main.700x0c.jpg", age: 21, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

taylor_swift=Celebrity.create(name:"Taylor Swift", image:"https://www.grammy.com/sites/com/files/styles/image_landscape_hero/public/taylorswift-hero-510837066.jpg?itok=-KPdXpCe", age: 17, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)

emily_clarke=Celebrity.create(name: "Emily Clarke", image:"https://noescinetodoloquereluce.com/wp-content/uploads/2016/11/emilia-clarke-800x445.jpg", age: 16, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

# thandie_newton=Celebrity.create(name: "Thandie Newton", image:"https://i.pinimg.com/originals/09/f2/08/09f2088f642e48765b79bf9280e40247.jpg", age: 17, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "white", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 1, wavy_hair: 0)

# tyra_banks=Celebrity.create(name: "Tyra Banks", image:"https://cdn.cliqueinc.com/cache/posts/258390/tyra-banks-pacific-palisades-home-258390-1527007456211-main.700x0c.jpg", age: 18, arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 1, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "asian", receding_hairline: 0, rosy_cheeks: 1, straight_hair: 0, wavy_hair: 1)

# zazie_beetz=Celebrity.create(name:"Zazie Beetz", image:"https://kenh14cdn.com/2018/2/7/dsc4517-15179857746511996920431.jpg", age: 21, arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 0, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "black", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

# zoe_kravitz=Celebrity.create(name: "Zoe Kravitz", image:"https://i.pinimg.com/236x/6c/44/d2/6c44d2aef996fa7174849e0bae5a16c3--smoked-eyes-center-part.jpg", age: 19, arched_eyebrows: 1, big_lips: 1, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 0, pointy_nose: 1, race: "black", receding_hairline: 0, rosy_cheeks: 0, straight_hair: 0, wavy_hair: 1)

# cdn=Friend.create(name:"Crystal", image: "https-//cdn.pixabay.com/photo/2014/08/28/08/31/model-429733_960_720.jpg", age: 24 , arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0,brown_hair: 1, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, wavy_hair: 1)

# srey=Friend.create(name:"Tiffany", image: "http-//www.srey-saat.com/wp-content/uploads/2018/04/Ha-Nui-Lee-Top-Most-Popular-Beautiful-Asian-Women-2018.jpg", age: 29 , arched_eyebrows: 0, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 1, pointy_nose: 0, race: "white" , receding_hairline: 0, rosy_cheeks: 0, wavy_hair: 0)
#
# tucu=Friend.create(name:"Amber", image:"http-//www.tucumanalas7.com.ar/u/fotografias/m/2018/8/21/f620x350-79713_110731_25.jpg",age: 31 , arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 0, narrow_eyes: 0, pale_skin: 1, pointy_nose: 1, race: "asian" , receding_hairline: 0, rosy_cheeks: 0, wavy_hair: 0)
#
# truelove=Friend.create(name:"Brenda", image:"https-//truelovedates.com/wp-content/uploads/2013/03/looking-up-1.jpg",age: 25 , arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 0, blonde_hair: 0,brown_hair: 1, bushy_eyebrows: 1, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "white", receding_hairline: 0, rosy_cheeks: 0, wavy_hair: 1)
#
# atila=Friend.create(name:"Angel", image:"https-//atilambalaj.com/wp-content/uploads/parser/short-hairstyles-for-black-women-natural-hair-1.jpg", age: 27 , arched_eyebrows: 1, big_lips: 0, big_nose: 0, black_hair: 1, blonde_hair: 0, brown_hair: 0, bushy_eyebrows: 0, chubby: 0, heavy_makeup: 1, high_cheekbones: 1, narrow_eyes: 0, pale_skin: 0, pointy_nose: 0, race: "black", receding_hairline: 1, rosy_cheeks: 1, wavy_hair: 1)
